config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}
  resources :days

  root "home#index"
  resources :sounds

  resources :photos do
    collection do
      post :sort
    end
  end

  resources :locations

end

app/models/day.rb
class Day < ActiveRecord::Base
  has_many :locations
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.all
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render :show, status: :created, location: @day }
      else
        format.html { render :new }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { render :show, status: :ok, location: @day }
      else
        format.html { render :edit }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url, notice: 'Day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:date, :path)
    end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.haml
= form_for(@day) do |f|
  - if @day.errors.any?
    #error_explanation
      %h2
        = pluralize(@day.errors.count, "error")
        prohibited this day from being saved:
      %ul
        - @day.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :date
    %br/
    = f.datetime_select :date
  .field
    = f.label :path
    %br/
    = f.text_field :path
  .actions
    = f.submit

app/views/days/edit.html.haml
%h1 Editing day
= render 'form'
= link_to 'Show', @day
|
\#{link_to 'Back', days_path}

app/views/days/index.html.haml
%h1 Listing days
%table
  %thead
    %tr
      %th Date
      %th Path
      %th{:colspan => "3"}
  %tbody
    - @days.each do |day|
      %tr
        %td= day.date
        %td= day.path
        %td= link_to 'Show', day
        %td= link_to 'Edit', edit_day_path(day)
        %td= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' }
%br
= link_to 'New Day', new_day_path

app/views/days/new.html.haml
%h1 New day
= render 'form'
= link_to 'Back', days_path

app/views/days/show.html.haml
%p#notice= notice
%p
  %strong Date:
  = @day.date
%p
  %strong Path:
  = @day.path
= link_to 'Edit', edit_day_path(@day)
|
\#{link_to 'Back', days_path}