config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}
  resources :days

  root "home#index"
  resources :sounds

  resources :photos do
    collection do
      post :sort
    end
  end

  resources :locations

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_many :sounds
  acts_as_commentable
  mount_uploader :photo, PhotoUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    # TODO:
    # 1st, author must be integer
    # 2nd, must track name and photo of authors from google
    # then we can default the author to the current user
    # @photo.author = current_user if @photo.author.nil?

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, photo: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, photo: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def sort
    params[:photo_ids].each_with_index do |id, index|
      Photo.where(id: id).update_all(position: index+1)
    end
    render json: nil, status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:author, :location_id, :photo, :remote_photo_url)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.haml
= form_for(@photo) do |f|
  - if @photo.errors.any?
    #error_explanation
      %h2
        = pluralize(@photo.errors.count, "error")
        prohibited this photo from being saved:
      %ul
        - @photo.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :author
    %br/
    = f.text_field :author
  .field
    = f.label :location_id
    %br/
    = f.number_field :location_id
  .field
    = f.label :photo
    = f.file_field :photo
  .actions
    = f.submit


-# @graph.get_object('10152423239794763/photos')

app/views/photos/edit.html.haml
%h1 Editing photo
= render 'form'
= link_to 'Show', @photo
|
\#{link_to 'Back', photos_path}

app/views/photos/index.html.haml
%h1 Listing photos
%table
  %thead
    %tr
      %th Author
      %th Location
      %th{:colspan => "3"}
  %tbody
    - @photos.each do |photo|
      %tr
        %td= photo.author
        %td= photo.location_id
        %td= link_to 'Show', photo
        %td= link_to 'Edit', edit_photo_path(photo)
        %td= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Photo', new_photo_path

app/views/photos/new.html.haml
%h1 New photo
= render 'form'
= link_to 'Back', photos_path

app/views/photos/show.html.haml
%p#notice= notice
%p
  %strong Author:
  = @photo.author
%p
  %strong Location:
  = @photo.location_id
%p
  %strong Photo:
  =image_tag @photo.photo.url
= link_to 'Edit', edit_photo_path(@photo)
|
\#{link_to 'Back', photos_path}