config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}
  resources :days

  root "home#index"
  resources :sounds

  resources :photos do
    collection do
      post :sort
    end
  end

  resources :locations

end

app/models/sound.rb
class Sound < ActiveRecord::Base
  has_many :photos
  acts_as_commentable
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  before_action :set_sound, only: [:show, :edit, :update, :destroy]

  # GET /sounds
  # GET /sounds.json
  def index
    @sounds = Sound.all
  end

  # GET /sounds/1
  # GET /sounds/1.json
  def show
  end

  # GET /sounds/new
  def new
    @sound = Sound.new
  end

  # GET /sounds/1/edit
  def edit
  end

  # POST /sounds
  # POST /sounds.json
  def create
    @sound = Sound.new(sound_params)

    respond_to do |format|
      if @sound.save
        format.html { redirect_to @sound, notice: 'Sound was successfully created.' }
        format.json { render :show, status: :created, location: @sound }
      else
        format.html { render :new }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sounds/1
  # PATCH/PUT /sounds/1.json
  def update
    respond_to do |format|
      if @sound.update(sound_params)
        format.html { redirect_to @sound, notice: 'Sound was successfully updated.' }
        format.json { render :show, status: :ok, location: @sound }
      else
        format.html { render :edit }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sounds/1
  # DELETE /sounds/1.json
  def destroy
    @sound.destroy
    respond_to do |format|
      format.html { redirect_to sounds_url, notice: 'Sound was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sound
      @sound = Sound.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sound_params
      params.require(:sound).permit(:name, :author, :location_id)
    end
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/views/sounds/_form.html.haml
= form_for(@sound) do |f|
  - if @sound.errors.any?
    #error_explanation
      %h2
        = pluralize(@sound.errors.count, "error")
        prohibited this sound from being saved:
      %ul
        - @sound.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :author
    %br/
    = f.text_field :author
  .field
    = f.label :location_id
    %br/
    = f.number_field :location_id
  .actions
    = f.submit

app/views/sounds/edit.html.haml
%h1 Editing sound
= render 'form'
= link_to 'Show', @sound
|
\#{link_to 'Back', sounds_path}

app/views/sounds/index.html.haml
%h1 Listing sounds
%table
  %thead
    %tr
      %th Name
      %th Author
      %th Location
      %th{:colspan => "3"}
  %tbody
    - @sounds.each do |sound|
      %tr
        %td= sound.name
        %td= sound.author
        %td= sound.location_id
        %td= link_to 'Show', sound
        %td= link_to 'Edit', edit_sound_path(sound)
        %td= link_to 'Destroy', sound, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Sound', new_sound_path

app/views/sounds/new.html.haml
%h1 New sound
= render 'form'
= link_to 'Back', sounds_path

app/views/sounds/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @sound.name
%p
  %strong Author:
  = @sound.author
%p
  %strong Location:
  = @sound.location_id
= link_to 'Edit', edit_sound_path(@sound)
|
\#{link_to 'Back', sounds_path}