config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}
  resources :days

  root "home#index"
  resources :sounds

  resources :photos do
    collection do
      post :sort
    end
  end

  resources :locations

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :photos
  has_many :sounds
  belongs_to :day

  def coordinates=(coords)
    self[:coordinates] = coords.class == String ? coords.gsub(/\(|\)/, '').split(', ') : coords
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :set_all_locations, only:[:edit, :new]
  skip_before_filter :authenticate_user!, only: :show

  def index
    @locations = Location.all
  end

  def show
  end

  def new
    @location = Location.new(location_params)
  end

  def edit
  end

  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

    def set_all_locations
      id = @location.nil? ? nil : @location.id
      @locations = Location.where.not(id: id).select(:id, :name)
    end

    def location_params
      params.require(:location).permit(:coordinates, :name)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.haml
= form_for(@location) do |f|
  - if @location.errors.any?
    #error_explanation
      %h2
        = pluralize(@location.errors.count, "error")
        prohibited this location from being saved:
      %ul
        - @location.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :coordinates
    %br/
    %p= @location.coordinates
    %input{type:'hidden', name:'coordinates[]', value:@location.coordinates[0]} 
    %input{type:'hidden', name:'coordinates[]', value:@location.coordinates[1]} 
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

.gallery.sort-mode{data:{location:@location.id}}
  %h2 Photos
  .button-toolbar
    .btn-group
      %button.btn.btn-default.dropdown-toggle{type:"button", data:{toggle:"dropdown"}, aria:{expanded:"false"}, title:'Import Photos'}
        %span.glyphicon.glyphicon-upload
      %ul.dropdown-menu{role:"menu"}
        %li
          %a.disk-import-trigger{href:"#"} From Disk
        %li
          %a.facebook-import-trigger{href:"#"} Facebook
        %li
          %a{href:"#"} Google+

    .mode-toggle.btn-radio-group.btn-group
      %label
        %input{type:'radio', name:'mode', checked:true}
        %span.btn.btn-default
          %i.glyphicon.glyphicon-move
      %label
        %input{type:'radio', name:'mode'}
        %span.btn.btn-default
          %i.glyphicon.glyphicon-ok-sign

    .batch-actions
      %button.btn.btn-danger.delete{disabled:true}
        %i.glyphicon.glyphicon-trash

      .btn-group
        %button.btn.btn-default.dropdown-toggle{type:"button", data:{toggle:"dropdown"}, aria:{expanded:"false"}, disabled:true}
          Move To
          %span.caret
        %ul.dropdown-menu{role:"menu"}
          - @locations.each do |loc|
            %li
              %a{href:"#", data:{location:{id:loc.id}}}= loc.name

  = form_tag sort_photos_path, class: 'sortable-gallery-form', remote: true do
    %ul.list-inline.photos.sortable
      - @location.photos.each do |photo|
        %li.photo{data:{id:photo.id}}
          %img{src:photo.photo.thumb_square_small.url}
          %input{type:"hidden", name:'photo_ids[]', value: photo.id}


  = form_for @location do |f|
    = f.s3_file_field :photos, :class => 'js-s3_file_field hidden-file-field', multiple: true #, :key => "/uploads/${timestamp}/${filename}"
    / .progress
    / .meter{ :style => "width: 0%" }


#album-browser.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type:"button", data:{dismiss:"modal"}, aria:{label:"Close"}}
          %span{aria:{hidden:"true"}}
            &times;
        %h4.modal-title Modal title
        %a.back back
        %p 
          Select
          %a.select-all All
          |
          %a.select-none None
        %button.btn.btn-primary.import-selected Import Selected
      .modal-body
        %ul.albums.list-inline
        %ul.album-photos.list-inline
      .modal-footer
        %button.btn.btn-default{type:"button", data:{dismiss:"modal"}} cancel

%script#photo-template{type:'x-tmpl-mustache'}
  %li.photo.thumb{data:{id:"{{id}}"}}
    .image-dummy{style:"background-image:url({{{source}}});"}
    %input{type:"hidden", name:'photo_ids[]', value:"{{id}}"}


-# TODO: move to locations.js.coffee

:javascript
  
  window.Admin.locationId = '#{@location.id}'
  
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '#{ENV["FB_APP_ID"]}',
      xfbml      : false,
      version    : 'v2.1'
    });
    console.log('init FB')
  };

  window.fbLogin = function(cb){
    console.log('check facebook logged in status')
    FB.getLoginStatus(function(res) {
      if (res.status === 'connected') {
        console.log('logged in, proceed.')
        cb();
      }
      else {
        console.log('not logged in, authenticate')
        FB.login(function(res){
          if(res.authResponse){
            cb();
          }
        },{scope : 'user_photos'});
      }
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

app/views/locations/edit.html.haml
%h1 Edit location
= render 'form'
|
\#{link_to 'Back', locations_path}

app/views/locations/index.html.haml
%h1 Listing locations
%table
  %thead
    %tr
      %th Coordinates
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @locations.each do |location|
      %tr
        %td= location.coordinates
        %td= location.name
        %td= link_to 'Show', location
        %td= link_to 'Edit', edit_location_path(location)
        %td= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Location', new_location_path

app/views/locations/new.html.haml
%h1 New location
= render 'form'
= link_to 'Back', locations_path

app/views/locations/show.html.haml
%p#notice= notice
%p
  %strong Coordinates:
  = @location.coordinates
%p
  %strong Name:
  = @location.name
= link_to 'Edit', edit_location_path(@location)
|
\#{link_to 'Back', locations_path}